-- Run once in Supabase SQL Editor if rebuilding the database.
-- Replace the owner UUID in your RLS policies with your Supabase Auth user UID.

create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  title text not null,
  type text not null default 'Activity',
  description text default '',
  tools text default '',
  learnings text default '',
  evidence_url text default '',
  thumbnail_url text default '',
  completed_on date not null,
  created_at timestamptz not null default now()
);

-- Skills use the same protected admin workflow as activities. Rows with
-- type = 'Skill' store the skill name in title and its level in description.
-- A private SkillMeta marker allows an intentionally empty skills list.

create table if not exists public.activity_comments (
  id bigint generated by default as identity primary key,
  activity_id bigint not null references public.activities(id) on delete cascade,
  visitor_name text not null,
  comment text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.site_feedback (
  id bigint generated by default as identity primary key,
  visitor_name text not null,
  feedback text not null,
  created_at timestamptz not null default now()
);

-- Privacy-friendly access records are stored with visitor_name set to
-- '__portfolio_visit_v1__'. They may contain device/browser details, a masked
-- public IP, and an IP-based approximate city/region. Raw IP addresses, exact
-- coordinates, and browser GPS data are not stored by the website.

-- Feedback and comment text use a versioned JSON envelope so their masked IP,
-- approximate location, device, and browser can be shown only in admin mode.
-- This keeps the existing table columns and remains compatible with older rows.

-- The current project's RLS policies are already configured in Supabase.
-- Keep RLS enabled and never expose a service-role key in website source.
